name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      run:
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        java -version
        
    - name: Verify Java Version
      run: java -version
